/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConfirmationChecklist {
  'dispatch' : Dispatch,
  'production' : Production,
  'preProduction' : PreProduction,
  'packaging' : Packaging,
}
export interface Dispatch {
  'transportBooked' : boolean,
  'dispatchDateConfirmed' : boolean,
  'trackingShared' : boolean,
  'clientInformed' : boolean,
}
export interface OrderData {
  'id' : bigint,
  'confirmationChecklist' : ConfirmationChecklist,
  'clientName' : string,
  'createdAt' : Time,
  'color' : string,
  'size' : Size,
  'dispatchDate' : Time,
  'productType' : string,
  'updatedAt' : Time,
  'quantity' : bigint,
  'orderNumber' : string,
  'overallStatus' : OverallStatus,
}
export interface OrderInput {
  'confirmationChecklist' : ConfirmationChecklist,
  'clientName' : string,
  'color' : string,
  'size' : Size,
  'dispatchDate' : Time,
  'productType' : string,
  'quantity' : bigint,
  'orderNumber' : string,
  'overallStatus' : OverallStatus,
}
export type OverallStatus = { 'completed' : null } |
  { 'dispatched' : null } |
  { 'inProduction' : null } |
  { 'waitingForApproval' : null } |
  { 'packaging' : null };
export interface Packaging {
  'quantityCounted' : boolean,
  'labelsCorrect' : boolean,
  'photosTaken' : boolean,
  'correctPackagingTypeUsed' : boolean,
}
export interface PreProduction {
  'sampleApproved' : boolean,
  'colorReferenceConfirmed' : boolean,
  'materialConfirmedAvailable' : boolean,
  'timelineCommitted' : boolean,
  'sizeConfirmed' : boolean,
}
export interface Production {
  'designFileCAD' : boolean,
  'colorMatchedWithSample' : boolean,
  'sizeVerifiedDuringProduction' : boolean,
  'yarnDyingProcess' : boolean,
}
export interface Size { 'height' : number, 'length' : number, 'width' : number }
export type Time = bigint;
export interface _SERVICE {
  'createOrder' : ActorMethod<[OrderInput], bigint>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderData>>,
  'getOrder' : ActorMethod<[bigint], OrderData>,
  'getOrdersByClientName' : ActorMethod<[string], Array<OrderData>>,
  'updateOrder' : ActorMethod<[bigint, OrderInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];