/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Dispatch = IDL.Record({
  'transportBooked' : IDL.Bool,
  'dispatchDateConfirmed' : IDL.Bool,
  'trackingShared' : IDL.Bool,
  'clientInformed' : IDL.Bool,
});
export const Production = IDL.Record({
  'designFileCAD' : IDL.Bool,
  'colorMatchedWithSample' : IDL.Bool,
  'sizeVerifiedDuringProduction' : IDL.Bool,
  'yarnDyingProcess' : IDL.Bool,
});
export const PreProduction = IDL.Record({
  'sampleApproved' : IDL.Bool,
  'colorReferenceConfirmed' : IDL.Bool,
  'materialConfirmedAvailable' : IDL.Bool,
  'timelineCommitted' : IDL.Bool,
  'sizeConfirmed' : IDL.Bool,
});
export const Packaging = IDL.Record({
  'quantityCounted' : IDL.Bool,
  'labelsCorrect' : IDL.Bool,
  'photosTaken' : IDL.Bool,
  'correctPackagingTypeUsed' : IDL.Bool,
});
export const ConfirmationChecklist = IDL.Record({
  'dispatch' : Dispatch,
  'production' : Production,
  'preProduction' : PreProduction,
  'packaging' : Packaging,
});
export const Size = IDL.Record({
  'height' : IDL.Float64,
  'length' : IDL.Float64,
  'width' : IDL.Float64,
});
export const Time = IDL.Int;
export const OverallStatus = IDL.Variant({
  'completed' : IDL.Null,
  'dispatched' : IDL.Null,
  'inProduction' : IDL.Null,
  'waitingForApproval' : IDL.Null,
  'packaging' : IDL.Null,
});
export const OrderInput = IDL.Record({
  'confirmationChecklist' : ConfirmationChecklist,
  'clientName' : IDL.Text,
  'color' : IDL.Text,
  'size' : Size,
  'dispatchDate' : Time,
  'productType' : IDL.Text,
  'quantity' : IDL.Nat,
  'orderNumber' : IDL.Text,
  'overallStatus' : OverallStatus,
});
export const OrderData = IDL.Record({
  'id' : IDL.Nat,
  'confirmationChecklist' : ConfirmationChecklist,
  'clientName' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Text,
  'size' : Size,
  'dispatchDate' : Time,
  'productType' : IDL.Text,
  'updatedAt' : Time,
  'quantity' : IDL.Nat,
  'orderNumber' : IDL.Text,
  'overallStatus' : OverallStatus,
});
export const OrderFileEntry = IDL.Record({
  'hash' : IDL.Text,
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addOrderFile' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'createOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [OrderData], ['query']),
  'getOrderFiles' : IDL.Func([IDL.Nat], [IDL.Vec(OrderFileEntry)], ['query']),
  'getOrdersByClientName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OrderData)],
      ['query'],
    ),
  'removeOrderFile' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOrder' : IDL.Func([IDL.Nat, OrderInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Dispatch = IDL.Record({
    'transportBooked' : IDL.Bool,
    'dispatchDateConfirmed' : IDL.Bool,
    'trackingShared' : IDL.Bool,
    'clientInformed' : IDL.Bool,
  });
  const Production = IDL.Record({
    'designFileCAD' : IDL.Bool,
    'colorMatchedWithSample' : IDL.Bool,
    'sizeVerifiedDuringProduction' : IDL.Bool,
    'yarnDyingProcess' : IDL.Bool,
  });
  const PreProduction = IDL.Record({
    'sampleApproved' : IDL.Bool,
    'colorReferenceConfirmed' : IDL.Bool,
    'materialConfirmedAvailable' : IDL.Bool,
    'timelineCommitted' : IDL.Bool,
    'sizeConfirmed' : IDL.Bool,
  });
  const Packaging = IDL.Record({
    'quantityCounted' : IDL.Bool,
    'labelsCorrect' : IDL.Bool,
    'photosTaken' : IDL.Bool,
    'correctPackagingTypeUsed' : IDL.Bool,
  });
  const ConfirmationChecklist = IDL.Record({
    'dispatch' : Dispatch,
    'production' : Production,
    'preProduction' : PreProduction,
    'packaging' : Packaging,
  });
  const Size = IDL.Record({
    'height' : IDL.Float64,
    'length' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const Time = IDL.Int;
  const OverallStatus = IDL.Variant({
    'completed' : IDL.Null,
    'dispatched' : IDL.Null,
    'inProduction' : IDL.Null,
    'waitingForApproval' : IDL.Null,
    'packaging' : IDL.Null,
  });
  const OrderInput = IDL.Record({
    'confirmationChecklist' : ConfirmationChecklist,
    'clientName' : IDL.Text,
    'color' : IDL.Text,
    'size' : Size,
    'dispatchDate' : Time,
    'productType' : IDL.Text,
    'quantity' : IDL.Nat,
    'orderNumber' : IDL.Text,
    'overallStatus' : OverallStatus,
  });
  const OrderData = IDL.Record({
    'id' : IDL.Nat,
    'confirmationChecklist' : ConfirmationChecklist,
    'clientName' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Text,
    'size' : Size,
    'dispatchDate' : Time,
    'productType' : IDL.Text,
    'updatedAt' : Time,
    'quantity' : IDL.Nat,
    'orderNumber' : IDL.Text,
    'overallStatus' : OverallStatus,
  });
  const OrderFileEntry = IDL.Record({
    'hash' : IDL.Text,
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addOrderFile' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'createOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [OrderData], ['query']),
    'getOrderFiles' : IDL.Func([IDL.Nat], [IDL.Vec(OrderFileEntry)], ['query']),
    'getOrdersByClientName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderData)],
        ['query'],
      ),
    'removeOrderFile' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOrder' : IDL.Func([IDL.Nat, OrderInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };