/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Size {
    height: number;
    length: number;
    width: number;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Packaging {
    quantityCounted: boolean;
    labelsCorrect: boolean;
    photosTaken: boolean;
    correctPackagingTypeUsed: boolean;
}
export interface OrderInput {
    confirmationChecklist: ConfirmationChecklist;
    clientName: string;
    color: string;
    size: Size;
    dispatchDate: Time;
    productType: string;
    quantity: bigint;
    orderNumber: string;
    overallStatus: OverallStatus;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OrderFileEntry {
    hash: string;
    name: string;
    mimeType: string;
    uploadedAt: bigint;
}
export interface OrderData {
    id: bigint;
    confirmationChecklist: ConfirmationChecklist;
    clientName: string;
    createdAt: Time;
    color: string;
    size: Size;
    dispatchDate: Time;
    productType: string;
    updatedAt: Time;
    quantity: bigint;
    orderNumber: string;
    overallStatus: OverallStatus;
}
export interface PreProduction {
    sampleApproved: boolean;
    colorReferenceConfirmed: boolean;
    materialConfirmedAvailable: boolean;
    timelineCommitted: boolean;
    sizeConfirmed: boolean;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ConfirmationChecklist {
    dispatch: Dispatch;
    production: Production;
    preProduction: PreProduction;
    packaging: Packaging;
}
export interface Production {
    designFileCAD: boolean;
    colorMatchedWithSample: boolean;
    sizeVerifiedDuringProduction: boolean;
    yarnDyingProcess: boolean;
}
export interface Dispatch {
    transportBooked: boolean;
    dispatchDateConfirmed: boolean;
    trackingShared: boolean;
    clientInformed: boolean;
}
export enum OverallStatus {
    completed = "completed",
    dispatched = "dispatched",
    inProduction = "inProduction",
    waitingForApproval = "waitingForApproval",
    packaging = "packaging"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addOrderFile(orderId: bigint, hash: string, name: string, mimeType: string): Promise<void>;
    createOrder(input: OrderInput): Promise<bigint>;
    deleteOrder(id: bigint): Promise<void>;
    getAllOrders(): Promise<Array<OrderData>>;
    getOrder(id: bigint): Promise<OrderData>;
    getOrderFiles(orderId: bigint): Promise<Array<OrderFileEntry>>;
    getOrdersByClientName(clientName: string): Promise<Array<OrderData>>;
    removeOrderFile(orderId: bigint, hash: string): Promise<void>;
    updateOrder(id: bigint, input: OrderInput): Promise<void>;
}
import type { ConfirmationChecklist as _ConfirmationChecklist, OrderData as _OrderData, OrderInput as _OrderInput, OverallStatus as _OverallStatus, Size as _Size, Time as _Time, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addOrderFile(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrderFile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrderFile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createOrder(arg0: OrderInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_OrderInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_OrderInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<OrderData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<OrderData> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_OrderData_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_OrderData_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderFiles(arg0: bigint): Promise<Array<OrderFileEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderFiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderFiles(arg0);
            return result;
        }
    }
    async getOrdersByClientName(arg0: string): Promise<Array<OrderData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByClientName(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByClientName(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeOrderFile(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeOrderFile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeOrderFile(arg0, arg1);
            return result;
        }
    }
    async updateOrder(arg0: bigint, arg1: OrderInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, to_candid_OrderInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, to_candid_OrderInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_OrderData_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderData): OrderData {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OverallStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OverallStatus): OverallStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    confirmationChecklist: _ConfirmationChecklist;
    clientName: string;
    createdAt: _Time;
    color: string;
    size: _Size;
    dispatchDate: _Time;
    productType: string;
    updatedAt: _Time;
    quantity: bigint;
    orderNumber: string;
    overallStatus: _OverallStatus;
}): {
    id: bigint;
    confirmationChecklist: ConfirmationChecklist;
    clientName: string;
    createdAt: Time;
    color: string;
    size: Size;
    dispatchDate: Time;
    productType: string;
    updatedAt: Time;
    quantity: bigint;
    orderNumber: string;
    overallStatus: OverallStatus;
} {
    return {
        id: value.id,
        confirmationChecklist: value.confirmationChecklist,
        clientName: value.clientName,
        createdAt: value.createdAt,
        color: value.color,
        size: value.size,
        dispatchDate: value.dispatchDate,
        productType: value.productType,
        updatedAt: value.updatedAt,
        quantity: value.quantity,
        orderNumber: value.orderNumber,
        overallStatus: from_candid_OverallStatus_n15(_uploadFile, _downloadFile, value.overallStatus)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    dispatched: null;
} | {
    inProduction: null;
} | {
    waitingForApproval: null;
} | {
    packaging: null;
}): OverallStatus {
    return "completed" in value ? OverallStatus.completed : "dispatched" in value ? OverallStatus.dispatched : "inProduction" in value ? OverallStatus.inProduction : "waitingForApproval" in value ? OverallStatus.waitingForApproval : "packaging" in value ? OverallStatus.packaging : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderData>): Array<OrderData> {
    return value.map((x)=>from_candid_OrderData_n13(_uploadFile, _downloadFile, x));
}
function to_candid_OrderInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_OverallStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OverallStatus): _OverallStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    confirmationChecklist: ConfirmationChecklist;
    clientName: string;
    color: string;
    size: Size;
    dispatchDate: Time;
    productType: string;
    quantity: bigint;
    orderNumber: string;
    overallStatus: OverallStatus;
}): {
    confirmationChecklist: _ConfirmationChecklist;
    clientName: string;
    color: string;
    size: _Size;
    dispatchDate: _Time;
    productType: string;
    quantity: bigint;
    orderNumber: string;
    overallStatus: _OverallStatus;
} {
    return {
        confirmationChecklist: value.confirmationChecklist,
        clientName: value.clientName,
        color: value.color,
        size: value.size,
        dispatchDate: value.dispatchDate,
        productType: value.productType,
        quantity: value.quantity,
        orderNumber: value.orderNumber,
        overallStatus: to_candid_OverallStatus_n10(_uploadFile, _downloadFile, value.overallStatus)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OverallStatus): {
    completed: null;
} | {
    dispatched: null;
} | {
    inProduction: null;
} | {
    waitingForApproval: null;
} | {
    packaging: null;
} {
    return value == OverallStatus.completed ? {
        completed: null
    } : value == OverallStatus.dispatched ? {
        dispatched: null
    } : value == OverallStatus.inProduction ? {
        inProduction: null
    } : value == OverallStatus.waitingForApproval ? {
        waitingForApproval: null
    } : value == OverallStatus.packaging ? {
        packaging: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
